name: "Automated Link Checker"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # every week on Monday at midnight
  push:
    branches: [sepenv]

jobs:
  LinkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Convert notebooks to Markdown
        run: |
          pip install nbconvert
          jupyter-nbconvert --to markdown teachopencadd/talktorials/**/talktorial.ipynb

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --accept '200..205, 403, 503, 504'
            --insecure
            --no-progress
            --exclude "http://localhost:.*"
            --exclude "http://127.0.0.1:.*"
            --exclude ".*\.mp4"
            --exclude ".*\.pdf"
            --exclude ".*\.png"
            --exclude ".*\.jpg"
            --exclude ".*\.py"
            --exclude "./**/*.md"
            --exclude "local://.*"
            "./teachopencadd/talktorials/**/talktorial.md"
            
          fail: true 
          output: lychee/report.md

      - name: Log Results to Summary
        run: |
          if [ -f lychee/report.md ]; then
            echo "## Link Check Results" >> $GITHUB_STEP_SUMMARY
            cat lychee/report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "## No broken links found!" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: broken-links-report
          path: lychee/report.md
