name: "Automated Link Checker"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # every week on Monday at midnight
  push:
    branches: [sepenv]

jobs:
  LinkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # --exclude-path and --exclude to filter out false positives
          args: >
            --verbose 
            --no-progress 
            --exclude "https://academic.oup.com/.*"
            --exclude "https://www.mdpi.com/.*"
            --exclude "https://go.drugbank.com/.*"
            --exclude "https://dx.doi.org/.*"
            --exclude "https://www.eurekaselect.com/.*"
            --exclude "https://www.quora.com/.*"
            --exclude "https://www.drugs.com/.*"
            --exclude "https://rest.uniprot.org/.*"
            --exclude "https://onlinelibrary.wiley.com/.*"
            --exclude "https://pubs.acs.org/.*"
            --exclude "https://doi.org/.*"
            --exclude ".*\{.*\}.*"
            --exclude ".*%.*"
            --exclude "http://localhost:.*"
            --exclude "http://127.0.0.1:.*"
            --exclude "https://fonts.googleapis.com/.*"
            --exclude "https://fonts.gstatic.com/.*"
            --exclude ".*\.mp4"
            --exclude ".*\.pdf"
            --exclude ".*\.png"
            --exclude "./**/*.ipynb" 
            --exclude "./**/*.py"
            --exclude ".*\.py/.*"
            --exclude "./**/*.md"
          fail: false 
          output: lychee/report.md

      - name: Log Results to Summary
        run: |
          if [ -f lychee/report.md ]; then
            echo "## Link Check Results" >> $GITHUB_STEP_SUMMARY
            cat lychee/report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "## No broken links found!" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: broken-links-report
          path: lychee/report.md