name: Docs

on:
  push:
    branches:
      - "master"
      - "maintenance/.+"
  pull_request:
    branches:
      - "master"
      - "dev"
      - "maintenance/.+"
  schedule:
    # every two weeks on Monday at 3 am
    - cron: "0 3/336 * * 1"

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.12"

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a
          df -h
          ulimit -a

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install package and dependencies
        shell: bash -l {0}
        run: |
          pip install sphinx
          pip install -r docs/requirement.txt

      - name: Environment Information
        shell: bash -l {0}
        run: |
          conda info --all
          conda list

      - name: Run Sphinx
        shell: bash -l {0}
        run: |
          cd docs
          make clean
          SPHINXOPTS="-j2 -T --keep-going" make html
          # Extra UGLY patch to fix PDF IFrame on T005
          cp talktorials/images/*.pdf _build/html/_images/
          sed -i 's|src="images/butina_full.pdf"|src="../_images/butina_full.pdf"|g' \
            _build/html/talktorials/T005_compound_clustering.html

      - name: Check URLs
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --retry-wait-time 2
            --max-retries 3
            --exclude "wiley\.com"
            --exclude "towardsdatascience\.com"
            --exclude "medium\.com"
            --exclude "quora\.com"
            --exclude "doi\.org"
            --exclude "pubs\.acs\.org"
            --exclude "ftp://"
            --exclude "machinelearningmastery\.com"
            --exclude "schrodinger\.com/training/videos"
            --exclude "icoa\.fr/pkidb"
            --exclude "\.txt$"
            --exclude "\.mp4$"
            --exclude "\.pdf$"
            --exclude "\.png$"
            "docs/_build/html/**/*.html" "README.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
