name: Website build

on:
  push:
    branches: ["master", "dev", "sepenv-ci"]
  pull_request:
    branches: ["master", "dev", "maintenance/.+"]
  schedule:
    - cron: "0 3/336 * * 1"

jobs:
  docs:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build Docs
        run: |
          uv run --group docs sphinx-build -b html docs docs/_build/html
        env:
          SPHINXOPTS: "-j2 -T --keep-going"

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --accept '200..205, 403, 503, 504'
            --insecure
            "docs/_build/html/**/*.html" "README.md"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4 # Updated to v4
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
