name: Run Talktorial

on:
  push:
    branches:
      - sepenv     
  pull_request:
    branches:
      - sepenv  

jobs:
  run-cli-scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # limit for the entire job (e.g., 15 minutes)
    strategy:
      fail-fast: false   # continue others even if one fails
      matrix:
        talktorial:
          - T001 # long runtime.
          - T002
          - T003 
          - T004
          - T005
          - T006
          - T007
          - T008
          - T009
          - T010
          - T011
          - T012
          - T013
          - T014
          - T015
          - T016
          - T017
          - T018
          - T019
          - T020
          - T021
          - T022
          - T023
          - T024
          - T025
          - T026
          - T027
          - T028
          - T033
          - T034
          - T035
          - T036
          - T037
          - T038

        #exclude:
          #- talktorial: T008 # opencadd
          #- talktorial: T010 # opencadd
          #- talktorial: T011 # opencadd
          #- talktorial: T012 # opencadd
          #- talktorial: T014 # opencadd
          #- talktorial: T015 # opencadd
          #- talktorial: T016 # opencadd
          #- talktorial: T018 # opencadd
          #- talktorial: T023 # opencadd
          #- talktorial: T025 # opencadd
          #- talktorial: T026 # opencadd
          #- talktorial: T019 # conda dependencies.
          #- talktorial: T033 # memory overload due to DL packages.
          #- talktorial: T034 # memory overload due to DL packages.
          #- talktorial: T035 # memory overload due to DL packages.
          #- talktorial: T036 # memory overload due to DL packages.
          #- talktorial: T037 # memory overload due to DL packages.
          #- talktorial: T038 # memory overload due to DL packages.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Conda
        run: |
          sudo apt-get update
          sudo apt-get install -y wget bzip2
          wget https://repo.anaconda.com/archive/Anaconda3-2024.06-1-Linux-x86_64.sh -O anaconda.sh
          bash anaconda.sh -b -p $HOME/anaconda
          echo "$HOME/anaconda/bin" >> $GITHUB_PATH
          source $HOME/anaconda/bin/activate

      - name: Check Python, Conda and set up environment
        shell: bash -l {0}
        run: |
          which python
          python --version
          conda run pip install pytest nbval
          conda list

      - name: Run Talktorial ${{ matrix.talktorial}}
        shell: bash -l {0}
        run: |
          echo "Running ${{ matrix.talktorial }}"
          conda run --no-capture-output python main.py -t ${{ matrix.talktorial}} --test True
